[package]
name = "bevy_surface"
version = "0.1.0"
authors = ["Marek Bernat <marek.bernat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bevy = { path="../bevy" }
bevy = "0.1.3"
num-complex = "0.3.0"
